apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-world
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Project
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app-root
  namespace: argocd
spec:
  project: hello-world
  source:
    repoURL: 'https://github.com/bernardjason/helloworld.git'
    targetRevision: 'HEAD'
    path: 'appinfra'
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world

