apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Values.name}}-app-root
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: {{.Values.repoURL | quote}}
    targetRevision: {{.Values.targetRevision | quote}}
    path: 'appinfra'
    helm:
      values: |
         name: '{{.Values.name}}'
         project: '{{.Values.project}}'
         message: '{{.Values.message}}'
         repoURL: '{{.Values.repoURL}}'
         targetRevision: '{{.Values.targetRevision}}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
