apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.name}}-ns
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Values.name}}-application
  namespace: argocd
spec:
  project: {{.Values.project}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: {{.Values.repoURL | quote}}
    targetRevision: {{.Values.targetRevision | quote}}
    path: 'appchart'
    helm:
      values: |
         name: '{{.Values.name}}'
         message: '{{.Values.message}}'
  destination:
    server: https://kubernetes.default.svc
    namespace: {{.Values.name}}-ns
