# apiVersion: v1
# kind: Namespace
# metadata:
#   name: hello-world
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-application
  namespace: hello-world
spec:
  project: hello-world
  namespace: hello-world
  source:
    repoURL: 'https://github.com/bernardjason/helloworld.git'
    targetRevision: 'HEAD'
    path: 'appchart'
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world

