---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  namespace: {{.Values.name}}-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{.Values.name}}-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  namespace: {{.Values.name}}-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}-pod
  template:
    metadata:
      labels:
        app: {{.Values.name}}-pod
    spec:
      containers:
        - name: {{.Values.name}}
          image: bernardjason/helloworld:2.0
          imagePullPolicy: IfNotPresent
          env:
          - name: MESSAGE
            value: '{{.Values.message}}'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "64Mi"
              cpu: "64m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.name}}-ingress
  namespace: {{.Values.name}}-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{{.Values.name}}
        pathType: Prefix
        backend:
          service:
            name: {{.Values.name}}-svc
            port:
              name: http

