---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.name}}-sa
  namespace: {{.Values.name}}-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Values.name}}-pod-reader
  namespace: {{.Values.name}}-ns
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.name}}-pod-reader
  namespace: {{.Values.name}}-ns
subjects:
  - kind: ServiceAccount
    name: {{.Values.name}}-sa
    namespace: {{.Values.name}}-ns
roleRef:
  kind: Role
  name: {{.Values.name}}-pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  namespace: {{.Values.name}}-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{.Values.name}}-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  namespace: {{.Values.name}}-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}-pod
  template:
    metadata:
      labels:
        app: {{.Values.name}}-pod
    spec:
      serviceAccountName: {{.Values.name}}-sa
      containers:
        - name: {{.Values.name}}
          image: bernardjason/helloworld:2.0
          imagePullPolicy: IfNotPresent
          env:
          - name: MESSAGE
            value: '{{.Values.message}}'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "32m"
            limits:
              memory: "32Mi"
              cpu: "32m"
